name: Run Tests on PR

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:8.0.1
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build tester image
        run: docker build --target tester -t tester-image .

      - name: Run tests
        env:
          MONGODB_HOST: localhost
        run: docker run --network host -e MONGODB_HOST tester-image
